# Generated by Django 3.2 on 2021-05-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_auto_20210503_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='nome_comentario',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome'),
        ),
    ]
