# Generated by Django 3.2 on 2021-05-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0004_alter_comentario_usario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='titulo_comentario',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título'),
        ),
    ]
